<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="1" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-18T12:25:43 HNE" name="Projet_RedmineSuite" finished-at="2023-12-18T12:26:22 HNE" duration-ms="39589">
    <groups>
    </groups>
    <test started-at="2023-12-18T12:25:43 HNE" name="Projet_RedmineTest" finished-at="2023-12-18T12:26:22 HNE" duration-ms="39589">
      <class name="testCases.TC_01_EnregistrerNouveauCompte">
        <test-method is-config="true" signature="setup()[pri:0, instance:testCases.TC_01_EnregistrerNouveauCompte@4fb0f2b9]" started-at="2023-12-18T12:26:01 HNE" name="setup" finished-at="2023-12-18T12:26:03 HNE" duration-ms="2078" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="test_Enregistrer_NouveauCompte()[pri:0, instance:testCases.TC_01_EnregistrerNouveauCompte@4fb0f2b9]" started-at="2023-12-18T12:26:03 HNE" name="test_Enregistrer_NouveauCompte" finished-at="2023-12-18T12:26:05 HNE" duration-ms="1493" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed expected [Votre compte a Ã©tÃ© crÃ©Ã© et attend l'approbation de l'administrateur.] but found [Votre compte a été créé et attend l'approbation de l'administrateur.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed expected [Votre compte a Ã©tÃ© crÃ©Ã© et attend l'approbation de l'administrateur.] but found [Votre compte a été créé et attend l'approbation de l'administrateur.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at testCases.TC_01_EnregistrerNouveauCompte.test_Enregistrer_NouveauCompte(TC_01_EnregistrerNouveauCompte.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Enregistrer_NouveauCompte -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.TC_01_EnregistrerNouveauCompte@4fb0f2b9]" started-at="2023-12-18T12:26:05 HNE" name="tearDown" finished-at="2023-12-18T12:26:05 HNE" duration-ms="360" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TC_01_EnregistrerNouveauCompte -->
      <class name="testCases.TC_03_CreationNouveauProjet_Redmine">
        <test-method is-config="true" signature="setup()[pri:0, instance:testCases.TC_03_CreationNouveauProjet_Redmine@6356695f]" started-at="2023-12-18T12:25:43 HNE" name="setup" finished-at="2023-12-18T12:25:48 HNE" duration-ms="4709" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="test_NouveauProjet()[pri:0, instance:testCases.TC_03_CreationNouveauProjet_Redmine@6356695f]" started-at="2023-12-18T12:25:48 HNE" name="test_NouveauProjet" finished-at="2023-12-18T12:26:01 HNE" duration-ms="12799" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testCases.TC_03_CreationNouveauProjet_Redmine.test_NouveauProjet(TC_03_CreationNouveauProjet_Redmine.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_NouveauProjet -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.TC_03_CreationNouveauProjet_Redmine@6356695f]" started-at="2023-12-18T12:26:01 HNE" name="tearDown" finished-at="2023-12-18T12:26:01 HNE" duration-ms="439" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TC_03_CreationNouveauProjet_Redmine -->
      <class name="testCases.TC_05_Copier_ProjetRedmine">
        <test-method is-config="true" signature="setup()[pri:0, instance:testCases.TC_05_Copier_ProjetRedmine@4a94ee4]" started-at="2023-12-18T12:26:15 HNE" name="setup" finished-at="2023-12-18T12:26:18 HNE" duration-ms="2540" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="test_Modifier()[pri:0, instance:testCases.TC_05_Copier_ProjetRedmine@4a94ee4]" started-at="2023-12-18T12:26:18 HNE" name="test_Modifier" finished-at="2023-12-18T12:26:22 HNE" duration-ms="4060" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed expected [Mise Ã  jour effectuÃ©e avec succÃ¨s.] but found [Mise à jour effectuée avec succès.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed expected [Mise Ã  jour effectuÃ©e avec succÃ¨s.] but found [Mise à jour effectuée avec succès.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at testCases.TC_05_Copier_ProjetRedmine.test_Modifier(TC_05_Copier_ProjetRedmine.java:61)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Modifier -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.TC_05_Copier_ProjetRedmine@4a94ee4]" started-at="2023-12-18T12:26:22 HNE" name="tearDown" finished-at="2023-12-18T12:26:22 HNE" duration-ms="321" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TC_05_Copier_ProjetRedmine -->
      <class name="testCases.TC_04_Modifier_ProjetRedmine">
        <test-method is-config="true" signature="setup()[pri:0, instance:testCases.TC_04_Modifier_ProjetRedmine@7b9a4292]" started-at="2023-12-18T12:26:09 HNE" name="setup" finished-at="2023-12-18T12:26:11 HNE" duration-ms="2272" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="test_Modifier()[pri:0, instance:testCases.TC_04_Modifier_ProjetRedmine@7b9a4292]" started-at="2023-12-18T12:26:11 HNE" name="test_Modifier" finished-at="2023-12-18T12:26:14 HNE" duration-ms="3111" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed expected [Mise Ã  jour effectuÃ©e avec succÃ¨s.] but found [Mise à jour effectuée avec succès.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed expected [Mise Ã  jour effectuÃ©e avec succÃ¨s.] but found [Mise à jour effectuée avec succès.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at testCases.TC_04_Modifier_ProjetRedmine.test_Modifier(TC_04_Modifier_ProjetRedmine.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Modifier -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.TC_04_Modifier_ProjetRedmine@7b9a4292]" started-at="2023-12-18T12:26:15 HNE" name="tearDown" finished-at="2023-12-18T12:26:15 HNE" duration-ms="363" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TC_04_Modifier_ProjetRedmine -->
      <class name="testCases.TC_02_ConnexionRedmine">
        <test-method is-config="true" signature="setup()[pri:0, instance:testCases.TC_02_ConnexionRedmine@79924b]" started-at="2023-12-18T12:26:05 HNE" name="setup" finished-at="2023-12-18T12:26:08 HNE" duration-ms="2375" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="ConnexionRedmine_Test()[pri:0, instance:testCases.TC_02_ConnexionRedmine@79924b]" started-at="2023-12-18T12:26:08 HNE" name="ConnexionRedmine_Test" finished-at="2023-12-18T12:26:09 HNE" duration-ms="931" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ConnexionRedmine_Test -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.TC_02_ConnexionRedmine@79924b]" started-at="2023-12-18T12:26:09 HNE" name="tearDown" finished-at="2023-12-18T12:26:09 HNE" duration-ms="341" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TC_02_ConnexionRedmine -->
    </test> <!-- Projet_RedmineTest -->
  </suite> <!-- Projet_RedmineSuite -->
</testng-results>
